# Nearest Neighbor example

In [2]:
import tensorflow as tf
import numpy as np

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('/tmp/data/', one_hot=True)

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [14]:
X_train, y_train = mnist.train.next_batch(5000)
X_test, y_test = mnist.test.next_batch(100)

In [7]:
# 矩阵与向量的减法
# 矩阵的每一个行向量与向量做减法
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
b = np.array([1, 1, 1])
print(a - b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# tf graph inputs
x_train = tf.placeholder(tf.float32, [None, 784])
x_test = tf.placeholder(tf.float32, [784]) # 每次输入一张图片测试

# L1 distance
# 矩阵x_train的每一个行向量减去向量x_test，然后对每个行向量的元素的绝对值求和，作为测试样本与该训练样本的距离
distance = tf.reduce_sum(tf.abs(tf.add(x_train, tf.negative(x_test))), reduction_indices=1)

# 找到训练集中于测试样本距离最近的样本，用该样本的类别作为测试样本的类别
y_pred = tf.argmin(distance, axis=0)

In [15]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    accuracy = 0.
    for i in range(len(X_test)):
        idx = sess.run(y_pred, feed_dict={x_train: X_train, x_test: X_test[i]})
        print('test sample', i, '\t prediction:', np.argmax(y_train[idx]), 'ground truth:', np.argmax(y_test[i]))
        if(np.argmax(y_train[idx]) == np.argmax(y_test[i])):
            accuracy += 1 / len(X_test)
    
    print('\nAccuracy:', accuracy)

test sample 0 	 prediction: 2 ground truth: 2
test sample 1 	 prediction: 1 ground truth: 1
test sample 2 	 prediction: 1 ground truth: 1
test sample 3 	 prediction: 7 ground truth: 7
test sample 4 	 prediction: 8 ground truth: 5
test sample 5 	 prediction: 0 ground truth: 0
test sample 6 	 prediction: 1 ground truth: 1
test sample 7 	 prediction: 0 ground truth: 0
test sample 8 	 prediction: 2 ground truth: 2
test sample 9 	 prediction: 6 ground truth: 6
test sample 10 	 prediction: 9 ground truth: 9
test sample 11 	 prediction: 2 ground truth: 2
test sample 12 	 prediction: 2 ground truth: 2
test sample 13 	 prediction: 3 ground truth: 3
test sample 14 	 prediction: 8 ground truth: 8
test sample 15 	 prediction: 2 ground truth: 2
test sample 16 	 prediction: 6 ground truth: 6
test sample 17 	 prediction: 2 ground truth: 2
test sample 18 	 prediction: 6 ground truth: 6
test sample 19 	 prediction: 0 ground truth: 0
test sample 20 	 prediction: 6 ground truth: 6
test sample 21 	 predic