# TensorFlow's Eager API
动态图机制

TensorFlow Eager 可以让你像使用 Numpy 那样轻松地构建神经网络，其巨大优势是提供了自动微分（无需再手书反向传播）。它还可以在 GPU 上运行，使神经网络训练速度明显加快。

谷歌大脑的开发团队曾表示，Eager Execution 的主要优点如下：

- 快速调试即刻的运行错误并通过 Python 工具进行整合

- 借助易于使用的 Python 控制流支持动态模型

- 为自定义和高阶梯度提供强大支持

- 适用于几乎所有可用的 TensorFlow 运算

In [1]:
from __future__ import absolute_import, division, print_function

1. absolute_import模块

```
from __future__ import absolute_import
```

在python2.4以前，默认的是相对引入，程序会首先在当前目录下查找目标模块，如果找不到才会去系统的默认目录中查找。这样就可能遇到问题，比如：程序的包结构是这样的，

```
pkg/
pkg/init.py
pkg/main.py
pkg/string.py
```

如果在main.py中调用import string，那么Python就会首先在当前目录下查找 string.py。若找到就会引入该模块。但是如果你想引入的是系统自带的标准string.py，这时候就需要提前调用from __future__ import absolute_import 了。这样的话，就可以用import string 来引入系统的标准string.py模块，利用from pkg import string引入当前目录下的string.py了。

2. division模块
在Python 2.x中，对于除法有两种情况，如果是整数相除，结果仍是整数，余数会被扔掉，这种除法叫“地板除”：

```
>>> 3/10
0
>>> 3/10.0
0.3
```

而在Python 3.x中，所有的除法都是精确除法，地板除用//表示：

```
>>> 3/10
0.3
>>> 3//10
0
```

要想在Python 2.x中使用Python 3.x的除法，可以通过__future__模块的division实现：

```
>>> from __future__ import division
>>> 3/10
0.3
>>> 3//10
0
```

3. print_function模块
在Python 2.x中，print方法后面既可以不加括号，又可以像函数一样添加括号。

```
print "hello, world!"
print("hello, world!")
```

但是在Python 3中，print方法仅作为一个函数使用，上面的第一种调用方法会报错。当我们想所有的print方法统一只能像函数一样调用时，就需要调用

```
from __future__ import print_function
```

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
print('set Eager mode')
tf.enable_eager_execution()
tfe = tf.contrib.eager

set Eager mode


In [7]:
print('define constant tensors')
a = tf.constant(2)
print('a:', a)
print('a = %i' % a)
b = tf.constant(3)
print('b:', b)
print('b = %i' % b)

define constant tensors
a: tf.Tensor(2, shape=(), dtype=int32)
a = 2
b: tf.Tensor(3, shape=(), dtype=int32)
b = 3


In [10]:
print('running operation without tf.Session')
c = a + b
print('c = %i' % c)
print('a * b = %i' % (a * b))

running operation without tf.Session
c = 5
a * b = 6


In [12]:
mat1 = tf.constant([
    [1., 2.],
    [3., 4.]
], dtype=tf.float32)
print('tensor:')
print('a = %s' % mat1)
print('')
mat2 = np.array([
    [5., 6.],
    [7., 8.]
], dtype=np.float32)
print('array:')
print('b = %s' % mat2)

tensor:
a = tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

array:
b = [[5. 6.]
 [7. 8.]]


In [13]:
mat3 = mat1 + mat2
print('mat1 + mat2 = %s' % mat3)

mat4 = tf.matmul(mat1, mat2)
print('mat1 * mat2 = %s' % mat4)

mat1 + mat2 = tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
mat1 * mat2 = tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


In [14]:
print('Iterate through tensor mat:')
for i in range(mat1.shape[0]):
    for j in range(mat1.shape[1]):
        print(mat1[i][j])

Iterate through tensor mat:
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
